#! /usr/bin/env zsh

RPM_TMP_DIR = $HOME/.caen-get
USER_ROOT = $HOME/.caen-root
YUMD_LINK = "https://github.com/Hilbert-Yaa/caen-get/releases/download/yum-utils-v4.3.1/yum-utils-4.3.1-1.mga9.noarch.rpm"
# Bootstrap
cg_bootstrap() {
    echo "@@Bootstrap caen-get ( > - < )..."
    mkdir -p $RPM_TMP_DIR
    mkdir -p $USER_ROOT
    curl -LJ $YUMD_LINK -o $RPM_TMP_DIR/yumd.rpm
    cd $USER_ROOT
    rpm2cpio $RPM_TMP_DIR/yumd.rpm | cpio -id
    export PATH="$USER_ROOT/usr/sbin:$USER_ROOT/usr/bin:$USER_ROOT/bin:$PATH"
    export MANPATH="$USER_ROOT/usr/share/man:$MANPATH"
    L='/lib:/lib64:/usr/lib:/usr/lib64'
    export LD_LIBRARY_PATH="$USER_ROOT/usr/lib:$USER_ROOT/usr/lib64:$L"
}

# Install
cg_install() {
    echo "@@TBD"
    PACKAGE_NAME = $2
    echo "@@Installing $PACKAGE_NAME..."
    sleep 1
}

cg_remove() {
    echo "@@TBD"
    PACKAGE_NAME = $2
    echo "@@Removing $PACKAGE_NAME..."
    sleep 1
}

cg_update() {
    echo "@@TBD"
    PACKAGE_NAME = $2
    echo "@@Updating $PACKAGE_NAME..."
    sleep 1
}

# handle arguments
echo $1 $2
while getopts ":bi" opt; do
    case ${opt} in
        b ) cg_bootstrap
        ;;
        i ) cg_install
        ;;
        r ) cg_remove
        ;;
        u ) #cg_upgrade
        ;;
        \? ) echo "@@Usage: $0 [-b : bootstrap] [-i <package_name>: install package] [-r <package_name>: remove package] [-u : <package_name>: update package]"
        ;;
    esac
done